'use client'
import { useState, useEffect } from 'react'
import Shell from '@/components/layout/Shell'
import PageHeader from '@/components/ui/PageHeader'
import EmptyState from '@/components/ui/EmptyState'
import DeleteBtn from '@/components/ui/DeleteBtn'
import { useFarmStore, useTotals } from '@/store/farmStore'
import { useRole } from '@/hooks/useRole'
import { fmt, fmtN, today } from '@/lib/utils'
import { Plus, Printer } from 'lucide-react'
import type { SaleRecord } from '@/types'

function printInvoice(r: SaleRecord) {
  const w = window.open('', '_blank')
  if (!w) return
  w.document.write(`
    <html><head><title>Invoice #${r.id.slice(0, 6).toUpperCase()}</title>
    <style>body{font-family:sans-serif;padding:40px;max-width:500px;margin:auto}h2{color:#0F6E56}.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee}.total{font-weight:600;font-size:18px}</style>
    </head><body>
    <h2>PFFMS — Invoice</h2>
    <p><strong>Invoice #:</strong> ${r.id.slice(0, 6).toUpperCase()}<br/>
    <strong>Date:</strong> ${r.date}<br/>
    <strong>Customer:</strong> ${r.customer || 'Walk-in'}</p>
    <div class="row"><span>Crates sold</span><span>${r.crates}</span></div>
    <div class="row"><span>Price per crate</span><span>₦${r.pricePerCrate.toLocaleString()}</span></div>
    <div class="row total"><span>Total</span><span>₦${r.total.toLocaleString()}</span></div>
    <div class="row"><span>Payment status</span><span>${r.status}</span></div>
    <br/><p style="color:#999;font-size:12px">Generated by PFFMS — Poultry Farm Financial Management System</p>
    </body></html>`)
  w.document.close()
  w.print()
}

const initForm = { date: today(), customer: '', crates: '', pricePerCrate: '', total: '', status: 'Paid' as const }

export default function SalesPage() {
  const { sales, addSale, deleteSale } = useFarmStore()
  const { totalRevenue, unpaidDebt } = useTotals()
  const { can } = useRole()
  const [form, setForm] = useState(initForm)
  const set = (k: string, v: string) => setForm((f: typeof initForm) => ({ ...f, [k]: v }))

  useEffect(() => {
    const c = Number(form.crates), p = Number(form.pricePerCrate)
    if (c && p) setForm(f => ({ ...f, total: String(c * p) }))
  }, [form.crates, form.pricePerCrate])

  function handleAdd() {
    if (!form.date || !form.crates || !form.pricePerCrate) return
    addSale({ date: form.date, customer: form.customer, crates: Number(form.crates), pricePerCrate: Number(form.pricePerCrate), total: Number(form.total) || Number(form.crates) * Number(form.pricePerCrate), status: form.status as any })
    setForm(initForm)
  }

  const sorted = [...sales].sort((a, b) => b.date.localeCompare(a.date))

  return (
    <Shell>
      <PageHeader title="Sales" subtitle="Egg sales and customer tracking" />
      <div className="grid grid-cols-3 gap-3 mb-5">
        <div className="kpi-card"><div className="kpi-label">Total revenue</div><div className="kpi-value text-brand-600">{fmt(totalRevenue)}</div></div>
        <div className="kpi-card"><div className="kpi-label">Outstanding debts</div><div className="kpi-value text-red-500">{fmt(unpaidDebt)}</div></div>
        <div className="kpi-card"><div className="kpi-label">Transactions</div><div className="kpi-value">{sales.length}</div></div>
      </div>

      {can.writeSales && (
      <div className="card mb-4">
        <div className="section-title">Record sale</div>
        <div className="form-row">
          <div className="form-group"><label className="form-label">Date</label><input type="date" className="input" value={form.date} onChange={e => set('date', e.target.value)} /></div>
          <div className="form-group"><label className="form-label">Customer</label><input className="input" placeholder="e.g. Mama Nkechi" value={form.customer} onChange={e => set('customer', e.target.value)} /></div>
        </div>
        <div className="form-row-3">
          <div className="form-group"><label className="form-label">Crates sold</label><input type="number" className="input" value={form.crates} onChange={e => set('crates', e.target.value)} /></div>
          <div className="form-group"><label className="form-label">Price per crate (₦)</label><input type="number" className="input" value={form.pricePerCrate} onChange={e => set('pricePerCrate', e.target.value)} /></div>
          <div className="form-group"><label className="form-label">Total (₦)</label><input type="number" className="input" placeholder="Auto" value={form.total} onChange={e => set('total', e.target.value)} /></div>
        </div>
        <div className="form-row">
          <div className="form-group"><label className="form-label">Payment status</label>
            <select className="input" value={form.status} onChange={e => set('status', e.target.value)}>
              <option>Paid</option><option>Unpaid</option><option>Part payment</option>
            </select>
          </div>
          <div className="flex items-end"><button className="btn btn-primary w-full" onClick={handleAdd}><Plus size={14} /> Record sale</button></div>
        </div>
      </div>
      )}

      <div className="card">
        <div className="section-title">Sales log</div>
        {sorted.length === 0 ? <EmptyState /> : (
          <div className="tbl-wrap">
            <table className="tbl">
              <thead><tr><th>Date</th><th>Customer</th><th>Crates</th><th>Price/crate</th><th>Total</th><th>Status</th><th></th><th></th></tr></thead>
              <tbody>
                {sorted.map(r => (
                  <tr key={r.id}>
                    <td>{r.date}</td>
                    <td className="font-medium">{r.customer || '—'}</td>
                    <td>{fmtN(r.crates)}</td>
                    <td>{fmt(r.pricePerCrate)}</td>
                    <td className="font-medium text-brand-600">{fmt(r.total)}</td>
                    <td><span className={`badge ${r.status === 'Paid' ? 'badge-green' : r.status === 'Unpaid' ? 'badge-red' : 'badge-amber'}`}>{r.status}</span></td>
                    <td><button className="btn text-xs py-1 px-2" onClick={() => printInvoice(r)}><Printer size={12} /> Invoice</button></td>
                    <td>{can.writeSales && <DeleteBtn onDelete={() => deleteSale(r.id)} />}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </Shell>
  )
}
